# Generated by Django 5.1.5 on 2025-04-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='immagini'),
        ),
    ]
