# Generated by Django 5.1.5 on 2025-04-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museo', '0002_opera_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opera',
            name='date',
            field=models.IntegerField(),
        ),
    ]
