# Generated by Django 5.1.5 on 2025-05-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museo', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
