# Generated by Django 5.1.5 on 2025-05-12 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museo', '0005_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='JackPot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='immagini')),
                ('messaggio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='immagini')),
            ],
        ),
        migrations.CreateModel(
            name='Giocata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativi', models.IntegerField()),
                ('date', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museo.user')),
                ('slot1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giocate_slot1', to='museo.slot')),
                ('slot2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giocate_slot2', to='museo.slot')),
                ('slot3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giocate_slot3', to='museo.slot')),
            ],
        ),
    ]
